version: "3"

services:
  nocode-tailewind:
    container_name: nocode-tailewind
    user: "root"

    build:
      context: . # ビルドに必要なファイルが存在するディレクトリのパスを指定
      dockerfile: Dockerfile.dev # ビルドに使用するDockerfileの名前を指定

    environment:
      - NODE_ENV=development

    volumes:
      # ホストのディレクトリとコンテナの/workspaceをマウント
      - type: bind
        source: .
        target: /workspace

    restart: always # コンテナが異常終了した場合に自動的に再起動

    ports:
      - 127.0.0.1:3000:3000 # ホストのポート3000をコンテナのポート3000にマッピング